[project]
name = "repeater"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "browser-use[video]>=0.11.9",
    "dotenv>=0.9.9",
]
